//
// STARTER CODE: main.cpp
//
// Adam T Koehler, PhD
// University of Illinois, Chicago
// CS 251, Fall 2022
//
// Project Original Variation By:
// Shanon Reckinger
// University of Illinois, Chicago
//
// This file is the driver for the huffman encoding application.
// Do not edit this file!
//

#include "mainprog.h"

int main()
{
   return go();
}